/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "on-primary-container": "#afc1ff",
        "on-tertiary-container": "#4bdca0",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-primary-fixed-variant": "#003ea6",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "secondary-container": "#d5e3fc",
        "surface-container-highest": "#e0e3e5",
        "primary": "#00328a",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "primary-container": "#0047bb",
        "surface-tint": "#2156ca",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#eff1f3",
        "secondary": "#515f74",
        "tertiary-container": "#005d3e",
        "inverse-primary": "#b3c5ff",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#3a485b",
        "on-tertiary-fixed": "#002113",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#434653",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#57657a",
        "surface": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d5e3fc",
        "tertiary": "#00432c",
        "on-primary-fixed": "#00174a",
        "secondary-fixed-dim": "#b9c7df",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#0d1c2e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
